export const aceThemes = [
  'ambiance',
  'chaos',
  'chrome',
  'clouds_midnight',
  'clouds',
  'cobalt',
  'crimson_editor',
  'dawn',
  'dracula',
  'dreamweaver',
  'eclipse',
  'github',
  'gob',
  'gruvbox',
  'idle_fingers',
  'iplastic',
  'katzenmilch',
  'kr_theme',
  'kuroir',
  'merbivore_soft',
  'merbivore',
  'mono_industrial',
  'monokai',
  'pastel_on_dark',
  'solarized_dark',
  'solarized_light',
  'sqlserver',
  'terminal',
  'textmate',
  'tomorrow_night_blue',
  'tomorrow_night_bright',
  'tomorrow_night_eighties',
  'tomorrow_night',
  'tomorrow',
  'twilight',
  'vibrant_ink',
  'xcode'
];

export const aceThemeOptions = aceThemes.map((theme) => ({
  label: theme,
  value: theme
}));
